spring:
  data:
    mongodb:
      uri: mongodb+srv://admin:admin@core-cluster.pb9sf.mongodb.net/logistics_db?retryWrites=true&w=majority
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${JWT_SET_URI:https://app.please-open.it/auth/realms/46f7c701-ae40-4d42-a7bd-7a3b42501768/protocol/openid-connect/certs}

logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
               MongoTemplate: DEBUG

server:
  port: ${SERVER_PORT:8081}
  compression:
    enabled: true

keycloak:
  auth-server-url: ${AUTH_SERVER_URL:https://app.please-open.it/auth}
  realm: ${REALM:46f7c701-ae40-4d42-a7bd-7a3b42501768}
  resource: ${CLIENT_ID:logistics-system-client}
  client-secret: ${CLIENT_SECRET:jeRBOiPh37EfhFaQ9gOcuEINYuSVn7AX}
  username: ${REALM_USERNAME:lastpeace14@gmail.com}
  password: ${REALM_USER_PASSWORD:123}