spring:
  data:
    mongodb:
      uri: mongodb+srv://admin:admin@core-cluster.pb9sf.mongodb.net/logistics_db?retryWrites=true&w=majority
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${JWT_SET_URI:https://app.please-open.it/auth/realms/bd9c17f0-3f44-438d-9133-0507836fe18d/protocol/openid-connect/certs}

logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
               MongoTemplate: DEBUG

server:
  port: ${SERVER_PORT:8081}
  compression:
    enabled: true

keycloak:
  auth-server-url: ${AUTH_SERVER_URL:https://app.please-open.it/auth}
  realm: ${REALM:bd9c17f0-3f44-438d-9133-0507836fe18d}
  resource: ${CLIENT_ID:my-client}
  client-secret: ${CLIENT_SECRET:OUPEpNq7rwBppzuPVIVEYWZEGqRirUhl}
  username: ${REALM_USERNAME:darkapollon3@gmail.com}
  password: ${REALM_USER_PASSWORD:qwer123}