spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:logistics_system_db}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:admin}
  flyway:
    baselineOnMigrate: true
    enabled: true
    schemas: public
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    open-in-view: false
    show-sql: false
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${JWT_SET_URI:https://localhost:8080/auth/realms/doco-dev/protocol/openid-connect/certs}

server:
  port: ${SERVER_PORT:8081}
  compression:
    enabled: true

keycloak:
  auth-server-url: ${AUTH_SERVER_URL:}
  realm: ${REALM:}
  resource: ${CLIENT_ID:}
  client-secret: ${CLIENT_SECRET:}
  username: ${REALM_USERNAME:}
  password: ${REALM_USER_PASSWORD:}